### ISSUE TITLE
Mouse highlighting is barely visible

### ISSUE THREAD

**Issue by Sinderella** [catppuccin/zellij#4]
I am using the mocha flavours on both alacritty and zellij. There is no visibility issue with alacritty alone.
However, with zellij, highlighting text to copy is barely visible as shown below ("yaml" is highlighted):

<img width="242" alt="CleanShot 2022-08-09 at 17 43 06@2x" src="https://user-images.githubusercontent.com/1926450/183709326-491e3279-d046-4890-9182-206c3eda1fb3.png">

**Comment by mainrs** [comment]
Is the last `yaml` highlighted? I would have thought you highlighted `test-` to be honest. Maybe @jaeheonji can help out here. They actually implemented V2.

**Comment by Sinderella** [comment]
`test-yaml` was originally highlighted by some other script. I just used `yaml` as an example as it's difficult to see highlighted text with the normal dark background.

Edit: Actually, with normal background, the highlighted would be the same colour so I cannot see the difference.

**Comment by jaeheonji** [comment]
@Sinderella Sorry for the late reply because I double-checked the zellij code.

> Edit: Actually, with normal background, the highlighted would be the same colour so I cannot see the difference.

Yes, I missed one fact. In zellij, the `bg` color is currently used for only mouse selection. 

In order to prevent overlapping of the background color of the terminal and the selection color of zelij, it would be better to change the color 'bg'.

I will make a fix ASAP
