### ISSUE TITLE
Zellij has moved to a new configuration format

### ISSUE THREAD

**Issue by harukayamazaki** [catppuccin/zellij#8]
```
Zellij has moved to a new configuration format (KDL - https://kdl.dev) and has now been run with an old YAML configuration/layout/theme file.
- Converting the following theme YAML files to KDL files in the same location:
/home/user/.config/zellij/themes/catppuccin.yaml => /home/user/.config/zellij/themes/catppuccin.kdl
The original file(s) will remain unmodified.
Will then use the new converted file(s) for this and the next runs.

No actions are required of you. Press ENTER to continue.


Failed to convert yaml config: Failed to parse yaml: Scan(ScanError { mark: Marker { index: 43, line: 2, col: 18 }, info: "mapping values are not allowed in this context" })
```

**Comment by harukayamazaki** [comment]
I did make my own catppuccin.kdl with catppuccin mocha as the default theme. Maybe it could help other users if they are having issues
[catppuccin.kdl.zip](https://github.com/catppuccin/zellij/files/10914241/catppuccin.kdl.zip)

**Comment by sgoudham** [comment]
Hey there @eight85, 

There's actually an ongoing PR #7 which has a lot of discussion about migrating this, An outcome of that discussion is that Catppuccin has now actually been "upstreamed" in the main zellij repository itself [here](https://github.com/zellij-org/zellij/blob/main/example/themes/catppuccin.kdl) 

Hope that helps! I believe @jaeheonji is doing some great work on trying to include themes by default in zelllij so that users will not have to copy-paste config in the future. From now on, I think we'll update the README to avoid any confusion. 

Apologies! and thanks for using Catppuccin ❤️

**Comment by skoch13** [comment]
It looks like the link provided by @sgoudham was updated to [this](https://github.com/zellij-org/zellij/blob/main/zellij-utils/assets/themes/catppuccin.kdl)
